import React from 'react';
import { ACCESS_TO_THE_SITE, ADDITIONAL_RULES_CONTENT, ADDITIONAL_RULES_EMPHASIS, TTG_ADDRESS, APPLICABILITY_ARBITRATION_CONTENT, APPLICABILITY_ARBITRATION_EMPHASIS, ARBITRATION_RULES_CONTENT, ARBITRATION_RULES_EMPHASIS, AUTHORITY_ARBITRATOR_CONTENT, AUTHORITY_ARBITRATOR_EMPHASIS, CERTAIN_RESTRICTIONS_CONTENT, CERTAIN_RESTRICTIONS_CONTENT_2, CERTAIN_RESTRICTIONS_EMPHASIS, CLAIMS_NOT_SUBJECT_CONTENT, CLAIMS_NOT_SUBJECT_CONTENT_1, CLAIMS_NOT_SUBJECT_CONTENT_2, CLAIMS_NOT_SUBJECT_CONTENT_3, CLAIMS_NOT_SUBJECT_EMPHASIS, CONFIDENTIALITY_CONTENT, CONFIDENTIALITY_EMPHASIS, CONTACT_INFORMATION, COOKIES_WEB_CONTENT, COOKIES_WEB_EMPHASIS, COPYRIGHT_CONTENT, COPYRIGHT_EMPHASIS, COPYRIGHT_POLICY, COPYRIGHT_POLICY_CONTENT_1, COPYRIGHT_POLICY_CONTENT_2, COPYRIGHT_POLICY_LIST_1, COPYRIGHT_POLICY_LIST_2, COPYRIGHT_POLICY_LIST_3, COPYRIGHT_POLICY_LIST_4, COPYRIGHT_POLICY_LIST_5, COPYRIGHT_POLICY_LIST_6, COPYRIGHT_POLICY_LIST_7, DISCLAIMERS, DISCLAIMERS_CONTENT_1, DISCLAIMERS_CONTENT_2, ELECTRONIC_COMMUNICATIONS_CONTENT, ELECTRONIC_COMMUNICATIONS_EMPHASIS, TTG_EMAIL, EMERGENCY_EQUITABLE_CONTENT, EMERGENCY_EQUITABLE_EMPHASIS, ENTIRE_TERMS_CONTENT, ENTIRE_TERMS_EMPHASIS, GENERAL, GENERAL_CONTENT, GOOGLE_DOUBLECLICK_CONTENT, GOOGLE_DOUBLECLICK_EMPHASIS, LIMITATION_LIABILITY, LIMITATION_LIABILITY_CONTENT_1, LIMITATION_LIABILITY_CONTENT_2, LIMITATION_LIABILITY_CONTENT_3, NOTICE_REQUIREMENT_CONTENT, NOTICE_REQUIREMENT_EMPHASIS, NO_SUPPORT_MAINTENANCE_CONTENT, NO_SUPPORT_MAINTENANCE_CONTENT_2, NO_SUPPORT_MAINTENANCE_EMPHASIS, OTHER_USERS_CONTENT, OTHER_USERS_CONTENT_2, OTHER_USERS_EMPHASIS, OUR_ADVERTISING_PARTNERS_CONTENT, OUR_ADVERTISING_PARTNERS_EMPHASIS, OUR_ADVERTISING_PARTNERS_LIST_1_LINK, OUR_ADVERTISING_PARTNERS_LIST_1_NAME, RIGHT_TO_WAIVE_CONTENT, RIGHT_TO_WAIVE_EMPHASIS, SEVERABILITY_CONTENT, SEVERABILITY_EMPHASIS, SMALL_CLAIMS_COURT_CONTENT, SMALL_CLAIMS_COURT_EMPHASIS, SUBJECT_TO_TERMS_EMPHASIS, SURVIVAL_OF_AGREEMENT_CONTENT, SURVIVAL_OF_AGREEMENT_EMPHASIS, TERMS_OF_USE, TERMS_OF_USE_SECTION_1, TERMS_OF_USE_SECTION_2, TERMS_OF_USE_SECTION_3, TERMS_OF_USE_SECTION_4, TERMS_OF_USE_VER_NUM, TERM_AND_TERMINATION_CONTENT, TERM_AND_TERMINATION_EMPHASIS, THIRD_PARTY_LINKS, THIRD_PARTY_LINKS_CONTENT, THIRD_PARTY_LINKS_EMPHASIS, TIME_LIMITS_CONTENT, TIME_LIMITS_EMPHASIS, WAIVER_OF_CLASS_CONTENT, WAIVER_OF_CLASS_EMPHASIS, WAIVER_OF_JURY_CONTENT, WAIVER_OF_JURY_EMPHASIS, YOUR_PRIVACY_CONTENT, YOUR_PRIVACY_EMPHASIS } from '../../utils/contents';

import "./InfoPages.css";

export default function TermsOfUsePage() {
    return (
       <div className="vertical-sm horizontal-sm specialFont body-xs termsOfUse">
           <div className="vertical-sm">
                <h3>{TERMS_OF_USE}</h3>
                <p><em>{TERMS_OF_USE_VER_NUM}</em></p>
                <p>{TERMS_OF_USE_SECTION_1}</p>
                <p>{TERMS_OF_USE_SECTION_2}</p>
                <p>{TERMS_OF_USE_SECTION_3}</p>
                <p>{TERMS_OF_USE_SECTION_4}</p>
            </div>

            <div className="vertical-sm">
                <h3>{ACCESS_TO_THE_SITE}</h3>
                <p><strong>{SUBJECT_TO_TERMS_EMPHASIS}</strong> {CLAIMS_NOT_SUBJECT_CONTENT}</p>
                <p><strong>{CERTAIN_RESTRICTIONS_EMPHASIS}</strong> {CLAIMS_NOT_SUBJECT_CONTENT}</p>
                <p>{CERTAIN_RESTRICTIONS_CONTENT_2}</p>

                <p><strong>{NO_SUPPORT_MAINTENANCE_EMPHASIS}</strong> {NO_SUPPORT_MAINTENANCE_CONTENT}</p>
                <p>{NO_SUPPORT_MAINTENANCE_CONTENT_2}</p>
            </div>

            <div className="vertical-sm">
                <h3>{THIRD_PARTY_LINKS}</h3>
                <p><strong>{THIRD_PARTY_LINKS_EMPHASIS}</strong> {THIRD_PARTY_LINKS_CONTENT}</p>

                <p><strong>{OTHER_USERS_EMPHASIS}</strong> {OTHER_USERS_CONTENT}</p>

                <p>{OTHER_USERS_CONTENT_2}</p>

                <p><strong>{COOKIES_WEB_EMPHASIS}</strong> {COOKIES_WEB_CONTENT}</p>

                <p><strong>{GOOGLE_DOUBLECLICK_EMPHASIS}</strong> {GOOGLE_DOUBLECLICK_CONTENT}</p>
                <p><strong>{OUR_ADVERTISING_PARTNERS_EMPHASIS}</strong> {OUR_ADVERTISING_PARTNERS_CONTENT}</p>

                <ul>
                    <p>{OUR_ADVERTISING_PARTNERS_LIST_1_NAME}</p>
                    <p>{OUR_ADVERTISING_PARTNERS_LIST_1_LINK}</p>
                </ul>
            </div>

            <div className="vertical-sm">
                <h3>{DISCLAIMERS}</h3>
                <p>{DISCLAIMERS_CONTENT_1}</p>
                <p>{DISCLAIMERS_CONTENT_2}</p>
            </div>

            <div className="vertical-sm">
                <h3>{LIMITATION_LIABILITY}</h3>
                <p>{LIMITATION_LIABILITY_CONTENT_1}</p>
                <p>{LIMITATION_LIABILITY_CONTENT_2}</p>
                <p>{LIMITATION_LIABILITY_CONTENT_3}</p>
                <p><strong>{TERM_AND_TERMINATION_EMPHASIS}</strong> {TERM_AND_TERMINATION_CONTENT}</p>
            </div>

            <div className="vertical-sm">
                <h3>{COPYRIGHT_POLICY}</h3>
                <p>{COPYRIGHT_POLICY_CONTENT_1}</p>
                <ul>
                    <li>{COPYRIGHT_POLICY_LIST_1}</li>
                    <li>{COPYRIGHT_POLICY_LIST_2}</li>
                    <li>{COPYRIGHT_POLICY_LIST_3}</li>
                    <li>{COPYRIGHT_POLICY_LIST_4}</li>
                    <li>{COPYRIGHT_POLICY_LIST_5}</li>
                    <li>{COPYRIGHT_POLICY_LIST_6}</li>
                    <li>{COPYRIGHT_POLICY_LIST_7}</li>
                </ul>
                <p>{COPYRIGHT_POLICY_CONTENT_2}</p>
            </div>

            <div className="vertical-sm">
                <h3>{GENERAL}</h3>
                <p>{GENERAL_CONTENT}</p>

                <p><strong>{APPLICABILITY_ARBITRATION_EMPHASIS}</strong> {APPLICABILITY_ARBITRATION_CONTENT}</p>
                <p><strong>{NOTICE_REQUIREMENT_EMPHASIS}</strong> {NOTICE_REQUIREMENT_CONTENT}</p>
                <p><strong>{ARBITRATION_RULES_EMPHASIS}</strong> {ARBITRATION_RULES_CONTENT}</p>
                <p><strong>{ADDITIONAL_RULES_EMPHASIS}</strong> {ADDITIONAL_RULES_CONTENT}</p>

                <p><strong>{TIME_LIMITS_EMPHASIS}</strong> {TIME_LIMITS_CONTENT}</p>
                <p><strong>{AUTHORITY_ARBITRATOR_EMPHASIS}</strong> {AUTHORITY_ARBITRATOR_CONTENT}</p>
                <p><strong>{WAIVER_OF_JURY_EMPHASIS}</strong> {WAIVER_OF_JURY_CONTENT}</p>
                <p><strong>{WAIVER_OF_CLASS_EMPHASIS}</strong> {WAIVER_OF_CLASS_CONTENT}</p>
                
                <p><strong>{CONFIDENTIALITY_EMPHASIS}</strong> {CONFIDENTIALITY_CONTENT}</p>
                <p><strong>{SEVERABILITY_EMPHASIS}</strong> {SEVERABILITY_CONTENT}</p>
                <p><strong>{RIGHT_TO_WAIVE_EMPHASIS}</strong> {RIGHT_TO_WAIVE_CONTENT}</p>
                <p><strong>{SURVIVAL_OF_AGREEMENT_EMPHASIS}</strong> {SURVIVAL_OF_AGREEMENT_CONTENT}</p>

                <p><strong>{SMALL_CLAIMS_COURT_EMPHASIS}</strong> {SMALL_CLAIMS_COURT_CONTENT}</p>
                <p><strong>{EMERGENCY_EQUITABLE_EMPHASIS}</strong> {EMERGENCY_EQUITABLE_CONTENT}</p>
                <p><strong>{CLAIMS_NOT_SUBJECT_EMPHASIS}</strong> {CLAIMS_NOT_SUBJECT_CONTENT}</p>

                <p>{CLAIMS_NOT_SUBJECT_CONTENT_1}</p>
                <p>{CLAIMS_NOT_SUBJECT_CONTENT_2}</p>
                <p>{CLAIMS_NOT_SUBJECT_CONTENT_3}</p>

                <p><strong>{ELECTRONIC_COMMUNICATIONS_EMPHASIS}</strong> {ELECTRONIC_COMMUNICATIONS_CONTENT}</p>
                <p><strong>{ENTIRE_TERMS_EMPHASIS}</strong> {ENTIRE_TERMS_CONTENT}</p>
                <p><strong>{YOUR_PRIVACY_EMPHASIS}</strong> {YOUR_PRIVACY_CONTENT}</p>
                <p><strong>{COPYRIGHT_EMPHASIS}</strong> {COPYRIGHT_CONTENT}</p>
            </div>

            <div className="vertical-sm">
                <h3>{CONTACT_INFORMATION}</h3>
                <p>{"Address: " + TTG_ADDRESS}</p>
                <p>{"Email: " + TTG_EMAIL}</p>
            </div>
        </div>
    );
}
